### ISSUE TITLE
Cloudflare APO Cache Purge not working on the latest version

### ISSUE THREAD

**Issue by nsgoyat** [cloudflare/Cloudflare-WordPress#484] opened 2022-06-04 06:36 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

6.0

### Cloudflare-WordPress version

4.10.0

### PHP version

8.1

### Expected result

The cache should be purged from the Cloudflare servers when we update the site content.

### Actual result

While using the latest version of the plugin and APO, if we update the site content, the Cloudflare Cache isn't purged and it still shows the old content.

### Steps to reproduce

1. Setup the latest Cloudflare Plugin on WordPress.
2. Enable APO settings.
3. Add a Page or article and get it cached on the Cloudflare Servers.
4. Update the article content from the WordPress dashboard and then open the URL in a private window of your browser.
5. You will notice that cache isn't purged from Cloudflare and it still serving the old content.

### Additional factoids

APO Cache Purging works fine when we switch the plugin to version 4.9.1

### References

It happened in the past too: https://github.com/cloudflare/Cloudflare-WordPress/issues/456

**Comment by zaidoon1** [comment] 2022-06-04 07:09
@nsgoyat can you provide an example of URLs that should be purged but are not being purged

**Comment by jacobbednarz** [comment] 2022-06-04 09:24
the output of WP_DEBUG would also be helpful here to diagnose whether this is intentional.

**Comment by jacobbednarz** [comment] 2022-06-04 09:27
just a note from #456, nothing changed functionality wise. the updated release was a fix for the user agent.

**Comment by nsgoyat** [comment] 2022-06-04 10:15
Hey Folks,
I Have captured the screencast showing the issue. With the latest version, the cache isn't getting purged. When I roll back to the older version, cache purge works fine.

https://photos.app.goo.gl/DiNG6wy9MadsfmJw5

**Comment by jacobbednarz** [comment] 2022-06-04 19:23
thanks but we need the URLs and debug information here.

**Comment by ediong** [comment] 2022-06-05 15:06
The concerns raised by this poster is correct. How do I know? I own a news website today.ng and updated the plugin to 4.10.0 about two days ago. I noticed since yesterday that my homepage and other pages were not updating immediately until after a few hours (about six hours or more). I spent most of the time trying to figure out the problem until I stumbled upon this link (https://community.cloudflare.com/t/latest-cloudflare-plugin-update-cache-issues/388638) in the community. It led me to think page and I downgraded as suggested by the poster. Everything is now back to normal. I think the problem is with the latest plugin and it should be looked into asap.

**Comment by zaidoon1** [comment] 2022-06-05 17:40
@ediong are you able to provide debug logs from the plugin as well as a list of URLs that should have been purged but were not? is https://www.today.ng/ one of them? I currently see bypass as the cache status for your home page so it wouldn't be cached to begin with:
<img width="664" alt="Screen Shot 2022-06-05 at 1 36 49 PM" src="https://user-images.githubusercontent.com/43054535/172063117-7cf80a06-ed84-4cc3-a7f8-c79dffd7840a.png">

**Comment by damzzzz** [comment] 2022-06-05 18:56
Same here.... Cache not cleared when updating a post... Come on, it's the very reason we have this plugin and pay for APO.
The last few versions of the plugin have all had issues with APO, not clearing the homepage on new posts, etc.
And now this....

**Comment by ediong** [comment] 2022-06-05 19:15
> @ediong are you able to provide debug logs from the plugin as well as a list of URLs that should have been purged but were not? is https://www.today.ng/ one of them?

Yes! https://www.today.ng is the main website with the issue. After downgrading, the purge now work as described. There's a problem with the latest version. In truth, you need to look into it. You can even stage a dummy site and test the plugin.

**Comment by jacobbednarz** [comment] 2022-06-05 21:37
closed by #485

**Closed by jacobbednarz** 2022-06-05 21:37 UTC

**Comment by damzzzz** [comment] 2022-06-05 22:22
Thanks, appreciate the quick fix!
