### ISSUE TITLE
APO cache is not cleared properly!

### ISSUE THREAD

**Issue by coolrecep** [cloudflare/Cloudflare-WordPress#426] opened 2021-07-20 19:31 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.8

### Cloudflare-WordPress version

4.5.1

### PHP version

8.0.8

### Expected result

Up to date version of the website on mobile.

### Actual result

A week old version.

### Steps to reproduce

How to reproduce (on desktop)

Step 1: fıre up your favourıte web browser ın ıncognıto mode
step 2: press f12 and enable mobıle mode by pressıng ctrl + shıft + m
step 3: open technopat.net
step 4: check the content dates, today ıs july 8 but cache ıs served from july 3!

How to reproduce (on mobıle)
Step 1: fıre up your favourıte web browser ın ıncognıto mode
step 2: open technopat.net
step 3: check the content dates, today ıs july 8 but cache ıs served from july 3!

### Additional factoids

I was using litespeed cache before, removed it completely.

### References

https://github.com/cloudflare/Cloudflare-WordPress/issues/404

**Comment by coolrecep** [comment] 2021-07-20 19:37
I had to create this ticket as the previous one was closed for no reason and after trying to explain the problem to cloudflare for months, I got this reply:

> Thank you for contacting Cloudflare Support.
> 
> We have run an automated check and the zones previously mentioned in this ticket have been either moved away from Cloudflare or deleted. This limits the troubleshooting actions our Support Engineers can take to resolve your issue. At this time, we will be marking this ticket as solved.
> 
> Alternatives to moving away your nameservers are:
> 
> Pause Cloudflare
> Go to the Overview tab in the Cloudflare dashboard.
> At the bottom right of this page, there is a link under Advanced Actions.
> Click Pause Cloudflare on Site
> 
> Pausing Cloudflare will stop all the proxying and use our services as DNS only.
> 
> Gray Cloud DNS records
> If the issue is happening only on specific sub-domains, you could gray cloud DNS records. This will stop proxying for that domain. You can do that in the DNS tab of your Cloudflare dashboard by clicking on the cloud icon.
> 
> In both cases, Cloudflare features such as DDoS protection, CDN caching, and free SSL will no longer be available.
> 
> This is an automated response, which we hope has answered your question.
> If you need further assistance, simply reply to this email to reach a Cloudflare Technical Support Engineer.
> 
> You can run tests for common issues on our Diagnostic Center.
> Search the Cloudflare Community for advice and insight.

**The zones previously mentioned in this ticket have been either moved away from Cloudflare or deleted?** Are you kidding me? Even my domain name is on cloudlfare. I'm a Pro customer for years! I have made no change. 

See it for yourself:

![image](https://user-images.githubusercontent.com/13221472/126384937-28c11308-9730-466c-83a2-b4f8c087455e.png)

Either fix this problem or disable the problematic service CF.

**Comment by jacobbednarz** [comment] 2021-07-20 20:31
This is a duplicate of #404 so keep an eye on that issue for updates. 

#404 was locked because the conversation was going off topic and had nothing to do with the issue at hand. If you have useful updates, that's fine however you only bog down efforts when you use it as a spot to complain instead of a move an issue forward. 

The response you got from Cloudflare support is completely irrelevant here. Support does not manage or maintain the SDKs or plugins; Engineering and the community does. 

Closing as a duplicate and again, watch #404 for updates.

**Closed** 2021-07-20 20:32 UTC
