### ISSUE TITLE
Version 4.5.0 broke all my WordPress installations: `bootstrap80.php: Failed to open stream`

### ISSUE THREAD

**Issue by AlexanderWillner** [cloudflare/Cloudflare-WordPress#417] opened 2021-06-02 07:09 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.7.2

### Cloudflare-WordPress version

4.5.0

### PHP version

8.0.6

### Expected result

Nothing specifically. Working WordPress installation.

### Actual result

```
Warning: require(/internal_path/wordpress/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-normalizer/bootstrap80.php): Failed to open stream: No such file or directory in /internal_path/wordpress/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-normalizer/bootstrap.php on line 15

Fatal error: Uncaught Error: Failed opening required '/internal_path/wordpress/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-normalizer/bootstrap80.php' (include_path='.:/usr/share/pear:/usr/share/php:/usr/share/pear:/usr/share/php') in /internal_path/wordpress/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-normalizer/bootstrap.php:15 Stack trace: #0 /internal_path/wordpress/wp-content/plugins/cloudflare/vendor/composer/autoload_real.php(69): require() #1 /internal_path/wordpress/wp-content/plugins/cloudflare/vendor/composer/autoload_real.php(59): composerRequire386a6fce91e17b37d63cb251597d5bd5() #2 /internal_path/wordpress/wp-content/plugins/cloudflare/vendor/autoload.php(7): ComposerAutoloaderInit386a6fce91e17b37d63cb251597d5bd5::getLoader() #3 /internal_path/wordpress/wp-content/plugins/cloudflare/cloudflare.loader.php(3): require_once('...') #4 /internal_path/wordpress/wp-content/plugins/cloudflare/cloudflare.php(49): require_once('...') #5 /internal_path/wordpress/wp-settings.php(391): include_once('...') #6 /internal_path/wordpress/wp-config.php(89): require_once('...') #7 /internal_path/wordpress/wp-load.php(37): require_once('...') #8 /internal_path/wordpress/wp-blog-header.php(13): require_once('...') #9 /internal_path/wordpress/index.php(17): require('...') #10 {main} thrown in /internal_path/wordpress/wp-content/plugins/cloudflare/vendor/symfony/polyfill-intl-normalizer/bootstrap.php on line 15

Notice: is_embed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /internal_path/wordpress/wp-includes/functions.php on line 5313

Notice: is_search was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /internal_path/wordpress/wp-includes/functions.php on line 5313
```

### Steps to reproduce

1. Have Auto-Updates for this plugin enabled
2. Wait for the page to break

### Additional factoids

Disabling the plugin by renaming ```/internal_path/wordpress/wp-content/plugins/cloudflare``` (e.g. via FTP) fixes the issue for now.

**Comment by AlexanderWillner** [comment] 2021-06-02 07:11
Actually a duplicate of #415 - however, the issue seems to be closed, which is *certainly* *not* how this issue should be handled. This update has to be pulled asap.

**Comment by AlexanderWillner** [comment] 2021-06-02 07:18
First look: probably reverting 59784aef8871ff77d0f10867c5b833bb6dbd7d5a for a release 4.5.1 might already help. But this is just out of the blue.

**Comment by jacobbednarz** [comment] 2021-06-02 08:01
As you have found, this is a duplicate of #415 and I don't have any further updates to share at this time.

**Closed by jacobbednarz** 2021-06-02 08:01 UTC
Labels: duplicate
