### ISSUE TITLE
Query Regarding Cloudflare Plugin

### ISSUE THREAD

**Issue by thegulshankumar** [cloudflare/Cloudflare-WordPress#191] opened 2017-06-29 11:20 UTC
Hi,

I am using Cloudflare plugin on my WordPress blog (https://www.gulshankumar.net). This plugin is helpful in many ways. However, I am not completely satisfied with this plugin. I am little skeptical about using it. 

I also found some bug, somehow I fixed it, but couldn't completely. So I would like to share in detail. I hope that my suggestion would be helpful for the improvement of this plugin.

**Issue -1** Regarding  HTTP Server Push
-------------------------
I am using Genesis Theme on my blog. It loads a small script for called html5shiv.js which is only supposed to be loaded for Internet Explorer only. But as I enable server push, it adds IE script in HTTP header. It results in one unwanted HTTP request. After digging a lot, I found that Server push is working mainly for the local domain, not for the external path. So firstly I dequeued the script and loaded it from the CDN path. It fixed the problem.

I want to say that, please bring two feature. 
1. Instead of suggesting adding some code in `wp-config.php` Please add a toggle button inside Dashboard. Once user do enable you could automatically add `define('CLOUDFLARE_HTTP2_SERVER_PUSH_ACTIVE', true);`
![image](https://user-images.githubusercontent.com/23408127/27683857-25ce8c86-5ce5-11e7-9778-624ea1b64ba0.png)
2. This plugin should provide an option for Server Push exclusion. I explained above why.
![image](https://user-images.githubusercontent.com/23408127/27684015-d02cda52-5ce5-11e7-87fe-39457b246384.png)

**Issue -2** Regarding Purge Cache 
-----------------------------------
Cloudflare plugin is powerful. It shouldn't be treated just as an addon, or a workaround for something. I firmly believe that it can turn out as a great cache manager, and provide better performance when carefully used with Cache Everything rule (Like I do).

I recently noticed that at some situation, this plugin does not purge page cache automatically which results in an unsatisfactory experience. I believe that this plugin should automatically purge cache in below situation. I want to see more hooks which can meet to general requirements and provide better user-experience.

 If we use Cache Everything rule, Cloudflare plugin must know to purge page level cache (except static files if cache validation exists) in all below situations. 

- When we update a widget
- When we deactivate/activate a plugin
- When we save any settings inside WordPress

Well, there are many situations, please [see how WP Rocket plugin handle](https://github.com/wp-media/wp-rocket/blob/8cc8fe16b953f578685600a05bfaab71edc94202/inc/common/purge.php).

Or, alternatively, you could add a button in WP toolbar to purge all page cache of Cloudflare Edge. This would be also a great help.

Thanks & Regards,
Gulshan

**Comment by thellimist** [comment] 2017-06-29 12:08
Hi Gulshan,

**About issue 1:**

Originally we thought it'd be a great idea to add HTTP/2 Server Push to all websites. We've encountered multiple problems regarding that. WordPress users are not tech savvy. They don't and should not know what files should be HTTP pushed. We've made a decision to hide the feature rather than delete it. That is the main reason why there isn't a card for HTTP/2 Server Push. We plan to keep HTTP/2 Server Push feature behind `CLOUDFLARE_HTTP2_SERVER_PUSH_ACTIVE ` flag and only let tech savvy users to figure it out and use it. Additionally Server Push is a feature which depends a lot on the site itself. We try to make the plugin as simple as possible. 

For the near future I can say we won't work on this feature. Though we're accepting Pull Requests. 

**About issue 2:**

You've mentioned mainly two things
- Increase the capability of Automatic Cache Purge
- Fixing the case where sometimes purging fails

both of them are good issues to solve.

Automatic Cache Purge started as a really simple feature. Since we've released it, we've been getting lots of user requests. Most of the time the user opens a PR with the automatization they want. I'll look into WP Rocket plugin sometime :)

Failure of purging is caused [here](https://github.com/cloudflare/Cloudflare-WordPress/blob/master/src/WordPress/Hooks.php#L119) and [here](https://github.com/cloudflare/Cloudflare-WordPress/blob/master/src/WordPress/Hooks.php#L158). As you can see they return `$isOK` value which is `true` if purge successful, `false` if not. The failure is caused by mostly internet being unreliable. One way to avoid this would be trying multiple times if purging fails. A good number of tries would be 3 in periods of 30 seconds. 

If you have time I'd recommend you to open PR's with the fix you want. For HTTP/2 please open a new issue so we can discuss on how you want to tackle the problem so I can suggest potential issues which might happen. 

Thanks for the detailed review and using the plugin 🙂

**Comment by IcyApril** [comment] 2017-06-29 12:11
Just to clarify regarding issue 2; if you want to use cache everything whilst using Cloudflare with WordPress, the only way to guarantee there will not be cache collisions is to use Bypass Cache on Cookie. Using Cache Everything without Bypass Cache on Cookie typically results in cache collisions where the admin bar or pre-filled user comment info is cached and served to other users. In order to prevent this please use Bypass Cache on Cookie as described here, any other configuration is done at your own risk: https://support.cloudflare.com/hc/en-us/articles/236166048-Caching-Static-HTML-with-WordPress-WooCommerce

**Comment by thegulshankumar** [comment] 2017-06-30 16:41
Hi,

Thanks for the valuable responses. 

Regarding server push, I have [fixed my problem](https://wordpress.org/support/topic/console-error-5/#post-9274549). However, it was not easy for me. So I was really hoping to see an exclusion field especially after enabling the hidden flag `CLOUDFLARE_HTTP2_SERVER_PUSH_ACTIVE`. Skipping this topic.

-------------------------------

The Automatic Cache Management is important for those users who are using Cache Everything rule. 

I would like to elaborate my point that how actually it's affecting to the visitors, how it can be reproduced, and what could be its possible solution.

As normal WordPress user, when first time, I noticed this feature I thought it can purge in all common situations. But that's not exactly happening.
![image](https://user-images.githubusercontent.com/23408127/27743180-c924ba56-5dd8-11e7-81e8-b89062b391e5.png)

Problem Summary: When we update widget title, changes don't reflect for our visitors if previously they have received HIT response.

**Live Practical**

-----------------------

**Required**
1. Two Browsers: Google Chrome, Country X; and Opera over VPN, set Country to Y(Aim: To check anonymous cache status).
2. One Page rule: `*example.com/* ` Cache level: Everything. Please don't set Edge Cache TTL as it will disregard no-cache control header.

**Going with below steps**
1. Visit homepage two times from anonymous location Y. Goal: To change CF-Cache-Status: MISS to HIT. Suppose you noticed the wrong title in your widget. What will do? You would like to change it, Right?
2. From real location X, Login to WordPress > Update Widget title > you will see changes live. As long CF-Cache-Status is MISS. Cool.
3. At this point, the plugin doesn't purge HTML cache which causes that anonymous traffics with HIT response (from location Y), will not see updated widget title.

**Possible solution**
We need to find out a way so we can purge page level cache. Meanwhile, I do this by updating the post. So difficult.  Alternatively, I don't want to purge everything as it will kill static files cache which is costly to earn HIT response again from various locations.

**Effect of problem**
Many!!!

Thanks & Regards,
Gulshan

**Comment by thegulshankumar** [comment] 2017-06-30 17:05
Hello, 
@IcyApril Cache Thanks for your kind concern, 

In my case, I am not facing cache collision. 

Assuming that the Edge cache is bypassed for WordPress logged in cookies. So, if I update the widget or anything, I will notice changes quickly in my browser. Good. But what about Anonymous visitors? Even after 30 seconds, the Automatic Cache Purge does not work.

Looking forward to seeing few more useful hooks so the plugin can efficiently purge Anonymous cache on every important action. (Ex, when we update any settings, make any changes).

Thanks & Regards,
Gulshan

**Comment by jwineman** [comment] 2017-06-30 17:12
Hey @thegulshankumar,

Our automatic cache purge functionality is limited by the WordPress hooks we can hook into for events that need cache purging.  You can see the list we currently use [here](https://github.com/cloudflare/Cloudflare-WordPress/blob/master/cloudflare.loader.php#L55-L58).  We currently only hook on events that require the _entire_ cache to be purged.  The Cloudflare API only allows purging by URL or by tag and I'm not aware of any WordPress functionality that easily allows us to map a Widget to the URLs that use it.  If you're aware of such a way we can consider adding it to the plugin.

Thanks,
John

**Comment by thegulshankumar** [comment] 2017-06-30 17:40
Sorry, I am not a Developer. Don't know how exactly it can be done. 

Here is something, I guess I need like this https://plugins.trac.wordpress.org/browser/clear-cache-for-widgets/trunk/clear-cache-for-widgets.php

Purge everything rule is something which will purge even for static files. I don't want to purge completely. That would be wastage of resources.  I only want to purge only dynamic part - HTML. Because my static files are never ever going to change. 

I do understand there is some API limit, 1200 every 5 minutes. It may be sufficient for me. As I don't have many page URLs to purge immediately.

For now, I am afraid if I will implement don't know what will be its effect, and I may loose code after the update too. 

One thing, I am using Code Snippets plugin. Is there any shortcut method like this which I can implement?
 Just an example: `add_action( 'wpcf7_save_contact_form', 'cloudflare_purge_by_urls' );`

Thanks & Regards,
Gulshan

**Comment by thellimist** [comment] 2017-06-30 18:53
Example of purging everything: https://github.com/cloudflare/Cloudflare-WordPress/blob/master/cloudflare.loader.php#L62

Example of purging by url: https://github.com/cloudflare/Cloudflare-WordPress/blob/master/cloudflare.loader.php#L72

If you want to purge additional URL's, add the URL you want to purge to the return value of [this](https://github.com/cloudflare/Cloudflare-WordPress/blob/master/src/WordPress/Hooks.php#L167-L242) function

Hope that helps.

Thanks

**Comment by zackproser** [comment] 2019-03-26 22:31
Thanks for the feedback. I'm going to close this as there's nothing actionable here for us to fix right now.

**Closed by zackproser** 2019-03-26 22:31 UTC
