### ISSUE TITLE
New Comments doesn't save after APO Enabled

### ISSUE THREAD

**Issue by negativedh** [cloudflare/Cloudflare-WordPress#307] opened 2020-10-10 18:48 UTC
We are using the internal wordpress comment system and after enabled the APO, everything looks perfect except comments. I feel that after We didn't get any comment a few days, and disabled immediately. After disabled APO, comment system works fine again.

I think, cached files doesn't post the comments to database because of not dynamic page or etc. 

Can you confirm that?

**Comment by pjatx** [comment] 2020-10-13 18:00
@negativedh Thanks for bringing this to our attention - we're working on resolving this now.

The issue is new comments are not currently triggering a cache purge. All comments should still be getting save as far as we know.

**Comment by negativedh** [comment] 2020-10-13 18:31
My problem isn't purging the page for see the new comments already.

Problem is, comments don't post to database so i can't show them in admin panel even.

**Comment by pjatx** [comment] 2020-10-13 18:57
Interesting - I'm not able to reproduce that on my end.

Can you locate the request in the network tab within inspect element and see if you notice anything strange?

**Closed** 2020-10-15 18:46 UTC

**Comment by manatarms** [comment] 2020-10-15 21:16
This was fixed in v3.8.5. Sorry for the trouble!

**Comment by negativedh** [comment] 2020-10-15 21:18
> This was fixed in v3.8.5. Sorry for the trouble!

Which one fixed? 
I think that job fixes to flush the cache when new comment send. 

But my problem is, comments aren't posting to wordpress database, that fix including too ?

**Comment by manatarms** [comment] 2020-10-15 21:22
We fixed the purging issue on comment save. We werent able to replicate the comments saving issue on our end.

**Comment by galbaras** [comment] 2020-10-16 05:31
Can you confirm that this only purges the page cache, not static objects?
